[tool.poetry]
name = "flavors_nlp"
version = "0.1.0"
description = ""
authors = ["EOF-D <END-OFD@pm.me>"]

[tool.poetry.dependencies]
python = "^3.11"
black = "^24.2.0"
isort = "^5.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
