repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Python
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: stable
    hooks:
      - id: isort

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.352
    hooks:
      - id: pyright

  # C++
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-tidy
      - id: cppcheck
      - id: uncrustify

  # Haskell
  - repo: https://github.com/pre-commit/mirrors-hlint
    rev: stable
    hooks:
      - id: hlint
