development:
  adapter: postgresql
  pool: 1

  host: localhost
  database: flavors-db-dev

production:
  adapter: postgresql
  pool: 5

  host: localhost
  database: flavors-db
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
