type Query {
  getRecipe(id: ID!): Recipe
}

type Mutation {}

type Recipe {
  id: ID!
  url: String!
  name: String!
  description: String!
  author: String!
  ratings: Int!
  ingredients: [Ingredient!]
  steps: [String!]
  times: Times!
  serves: Int!
  difficult: String!
}

type Ingredient {
  name: String!
  unit: String!
  quantity: String!
  preparation: String
}

type Times {
  preparation: String!
  cooking: String!
}
