type Query {
  getRecipe(id: ID!): Recipe!
  getRecipeByTitle(title: String!): Recipe!
  getRecipeByIngredients(ingredients: [String!]!): [Recipe!]!
  getRecipesByCuisine(cuisine: Cuisine!): [Recipe!]!
  getRecipes: [Recipe!]!
}

type Mutation {
  addRecipe(
    title: String!
    description: String!
    ingredients: [IngredientInput!]!
    instructions: [String!]!
    cuisine: Cuisine!
  ): Recipe!

  removeRecipe(id: ID!): Recipe
}

input IngredientInput {
  name: String!
  quantity: String!
  unit: String!
}

type Recipe {
  id: ID!
  author: String!
  name: String!
  description: String!
  instructions: [String!]!
  ingredients: [Ingredient!]!
}

type Ingredient {
  id: ID!
  name: String!
  quantity: String!
  unit: String!
}

enum Cuisine {
  AMERICAN,
  ASIAN,
  FRENCH,
  ITALIAN,
  MEXICAN,
  OTHER
}
